<?php

namespace DoctrineORMModule\Proxy\__CG__\Projects\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Flats extends \Projects\Entity\Flats implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'id', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'floor', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'flatNo', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'status', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'flatArea', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'flatType', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'buildingId', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'projectId', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'createdBy', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'dateCreated', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'building_details', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'project_details'];
        }

        return ['__isInitialized__', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'id', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'floor', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'flatNo', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'status', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'flatArea', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'flatType', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'buildingId', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'projectId', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'createdBy', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'dateCreated', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'building_details', '' . "\0" . 'Projects\\Entity\\Flats' . "\0" . 'project_details'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Flats $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFloor($floor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFloor', [$floor]);

        return parent::setFloor($floor);
    }

    /**
     * {@inheritDoc}
     */
    public function getFloor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFloor', []);

        return parent::getFloor();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlatNo($flatNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlatNo', [$flatNo]);

        return parent::setFlatNo($flatNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlatNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlatNo', []);

        return parent::getFlatNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlatArea($flatArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlatArea', [$flatArea]);

        return parent::setFlatArea($flatArea);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlatArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlatArea', []);

        return parent::getFlatArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlatType($flatType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlatType', [$flatType]);

        return parent::setFlatType($flatType);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlatType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlatType', []);

        return parent::getFlatType();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuildingId($buildingId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuildingId', [$buildingId]);

        return parent::setBuildingId($buildingId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuildingId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuildingId', []);

        return parent::getBuildingId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectId($projectId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectId', [$projectId]);

        return parent::setProjectId($projectId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectId', []);

        return parent::getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', [$dateCreated]);

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', []);

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuildingDetails(\Projects\Entity\Buildings $buildingDetails = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuildingDetails', [$buildingDetails]);

        return parent::setBuildingDetails($buildingDetails);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuildingDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuildingDetails', []);

        return parent::getBuildingDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectDetails(\Projects\Entity\Projects $projectDetails = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectDetails', [$projectDetails]);

        return parent::setProjectDetails($projectDetails);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectDetails', []);

        return parent::getProjectDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentSqFeetRate($currentSqFeetRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentSqFeetRate', [$currentSqFeetRate]);

        return parent::setCurrentSqFeetRate($currentSqFeetRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentSqFeetRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentSqFeetRate', []);

        return parent::getCurrentSqFeetRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setFloorRise($floorRise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFloorRise', [$floorRise]);

        return parent::setFloorRise($floorRise);
    }

    /**
     * {@inheritDoc}
     */
    public function getFloorRise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFloorRise', []);

        return parent::getFloorRise();
    }

    /**
     * {@inheritDoc}
     */
    public function setDevCharges($devCharges)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDevCharges', [$devCharges]);

        return parent::setDevCharges($devCharges);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevCharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevCharges', []);

        return parent::getDevCharges();
    }

    /**
     * {@inheritDoc}
     */
    public function setClubMembershipCharges($clubMembershipCharges)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClubMembershipCharges', [$clubMembershipCharges]);

        return parent::setClubMembershipCharges($clubMembershipCharges);
    }

    /**
     * {@inheritDoc}
     */
    public function getClubMembershipCharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClubMembershipCharges', []);

        return parent::getClubMembershipCharges();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdvanceMaintanance($advanceMaintanance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdvanceMaintanance', [$advanceMaintanance]);

        return parent::setAdvanceMaintanance($advanceMaintanance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdvanceMaintanance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdvanceMaintanance', []);

        return parent::getAdvanceMaintanance();
    }

    /**
     * {@inheritDoc}
     */
    public function setParkingCharges($parkingCharges)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParkingCharges', [$parkingCharges]);

        return parent::setParkingCharges($parkingCharges);
    }

    /**
     * {@inheritDoc}
     */
    public function getParkingCharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParkingCharges', []);

        return parent::getParkingCharges();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalCost($totalCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalCost', [$totalCost]);

        return parent::setTotalCost($totalCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalCost', []);

        return parent::getTotalCost();
    }

}
