<?php

namespace DoctrineORMModule\Proxy\__CG__\Projects\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Buildings extends \Projects\Entity\Buildings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'id', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'projectId', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'name', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'totalFloors', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'totalFlats', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'flatPerFloor', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'flatStartFloor', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'sqFeetArea', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'currentSqFeetRate', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'floorRise', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'floorRiseStarts', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'devCharges', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'paymentSlab', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'clubMembershipCharges', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'advanceMaintanace', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'parkingCharges', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'flatType', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'buildingStatus', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'floorPlans', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'description', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'status', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'elevation', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'createdBy', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'dateCreated', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'project'];
        }

        return ['__isInitialized__', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'id', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'projectId', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'name', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'totalFloors', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'totalFlats', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'flatPerFloor', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'flatStartFloor', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'sqFeetArea', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'currentSqFeetRate', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'floorRise', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'floorRiseStarts', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'devCharges', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'paymentSlab', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'clubMembershipCharges', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'advanceMaintanace', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'parkingCharges', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'flatType', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'buildingStatus', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'floorPlans', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'description', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'status', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'elevation', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'createdBy', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'dateCreated', '' . "\0" . 'Projects\\Entity\\Buildings' . "\0" . 'project'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Buildings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectId($projectId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectId', [$projectId]);

        return parent::setProjectId($projectId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectId', []);

        return parent::getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalFloors($totalFloors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalFloors', [$totalFloors]);

        return parent::setTotalFloors($totalFloors);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalFloors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalFloors', []);

        return parent::getTotalFloors();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalFlats($totalFlats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalFlats', [$totalFlats]);

        return parent::setTotalFlats($totalFlats);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalFlats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalFlats', []);

        return parent::getTotalFlats();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlatPerFloor($flatPerFloor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlatPerFloor', [$flatPerFloor]);

        return parent::setFlatPerFloor($flatPerFloor);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlatPerFloor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlatPerFloor', []);

        return parent::getFlatPerFloor();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlatStartFloor($flatStartFloor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlatStartFloor', [$flatStartFloor]);

        return parent::setFlatStartFloor($flatStartFloor);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlatStartFloor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlatStartFloor', []);

        return parent::getFlatStartFloor();
    }

    /**
     * {@inheritDoc}
     */
    public function setSqFeetArea($sqFeetArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSqFeetArea', [$sqFeetArea]);

        return parent::setSqFeetArea($sqFeetArea);
    }

    /**
     * {@inheritDoc}
     */
    public function getSqFeetArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSqFeetArea', []);

        return parent::getSqFeetArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentSqFeetRate($currentSqFeetRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentSqFeetRate', [$currentSqFeetRate]);

        return parent::setCurrentSqFeetRate($currentSqFeetRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentSqFeetRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentSqFeetRate', []);

        return parent::getCurrentSqFeetRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setFloorRise($floorRise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFloorRise', [$floorRise]);

        return parent::setFloorRise($floorRise);
    }

    /**
     * {@inheritDoc}
     */
    public function getFloorRise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFloorRise', []);

        return parent::getFloorRise();
    }

    /**
     * {@inheritDoc}
     */
    public function setFloorRiseStarts($floorRiseStarts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFloorRiseStarts', [$floorRiseStarts]);

        return parent::setFloorRiseStarts($floorRiseStarts);
    }

    /**
     * {@inheritDoc}
     */
    public function getFloorRiseStarts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFloorRiseStarts', []);

        return parent::getFloorRiseStarts();
    }

    /**
     * {@inheritDoc}
     */
    public function setDevCharges($devCharges)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDevCharges', [$devCharges]);

        return parent::setDevCharges($devCharges);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevCharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevCharges', []);

        return parent::getDevCharges();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentSlab($paymentSlab)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentSlab', [$paymentSlab]);

        return parent::setPaymentSlab($paymentSlab);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentSlab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentSlab', []);

        return parent::getPaymentSlab();
    }

    /**
     * {@inheritDoc}
     */
    public function setClubMembershipCharges($clubMembershipCharges)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClubMembershipCharges', [$clubMembershipCharges]);

        return parent::setClubMembershipCharges($clubMembershipCharges);
    }

    /**
     * {@inheritDoc}
     */
    public function getClubMembershipCharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClubMembershipCharges', []);

        return parent::getClubMembershipCharges();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdvanceMaintanace($advanceMaintanace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdvanceMaintanace', [$advanceMaintanace]);

        return parent::setAdvanceMaintanace($advanceMaintanace);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdvanceMaintanace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdvanceMaintanace', []);

        return parent::getAdvanceMaintanace();
    }

    /**
     * {@inheritDoc}
     */
    public function setParkingCharges($parkingCharges)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParkingCharges', [$parkingCharges]);

        return parent::setParkingCharges($parkingCharges);
    }

    /**
     * {@inheritDoc}
     */
    public function getParkingCharges()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParkingCharges', []);

        return parent::getParkingCharges();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlatType($flatType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlatType', [$flatType]);

        return parent::setFlatType($flatType);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlatType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlatType', []);

        return parent::getFlatType();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuildingStatus($buildingStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuildingStatus', [$buildingStatus]);

        return parent::setBuildingStatus($buildingStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuildingStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuildingStatus', []);

        return parent::getBuildingStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setFloorPlans($floorPlans)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFloorPlans', [$floorPlans]);

        return parent::setFloorPlans($floorPlans);
    }

    /**
     * {@inheritDoc}
     */
    public function getFloorPlans()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFloorPlans', []);

        return parent::getFloorPlans();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setElevation($elevation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setElevation', [$elevation]);

        return parent::setElevation($elevation);
    }

    /**
     * {@inheritDoc}
     */
    public function getElevation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElevation', []);

        return parent::getElevation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', [$dateCreated]);

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', []);

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setProject(\Projects\Entity\Projects $project = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProject', [$project]);

        return parent::setProject($project);
    }

    /**
     * {@inheritDoc}
     */
    public function getProject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProject', []);

        return parent::getProject();
    }

}
