<?php
$title = $this->translate('Sign in');
$this->headTitle($title);

$this->mainMenu()->setActiveItemId('login');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Email address',
    'required' => true,
    'autofocus' => true
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Password',
    'required' => true,
    ]);
?>
      <div class="login-container bg-white">
        <div class="p-l-30 m-l-15 p-r-30 m-r-15 p-t-30 m-t-20 sm-p-l-10 sm-p-r-10 sm-p-t-20">
           <?php 
			  //$path = $_SERVER['DOCUMENT_ROOT'].$this->basePath()."/uploads/".$this->SystemSettings()->getCompanyLogo();
			  //echo (file_exists($path)? '<img class="m-t-5" src="'.$this->basePath().'/uploads/logo.png" height="30"/>': '<i class="fa fa-anchor"></i><span>PlinthstoneLMS</span>');			  
			  echo '<img class="m-t-5" src="'.$this->basePath().'/uploads/logo.png" height="40"/>';
?>
            <p class="p-t-5"><?php echo $this->translate('Sign into your PlinthstoneLMS account') ?></p>

            <form id="form-login" class="p-t-15" role="form" method="post">

                <div class="form-group form-group-default">
                   <?= $this->formLabel($form->get('email')); ?>
                    <div class="controls">                                  
					<?= $this->formElement($form->get('email')); ?>            
                    </div>
                </div>


                <div class="form-group form-group-default">
                    <?= $this->formLabel($form->get('password')); ?>            
                    <div class="controls">
                     <?= $this->formElement($form->get('password')); ?>
                    </div>
                </div>
				
			<div class="row">
                    <div class="col-md-12 no-padding sm-p-l-10">	
			<?php if ($isLoginError): ?>
            <div class="alert alert-warning" role="alert">
                <?php echo $this->translate('Incorrect login and/or password. ') ?>
                <a href="<?= $this->url('reset-password') ?>"><?php echo $this->translate('Forgot password?') ?></a>
            </div>
            <?php endif; ?>
			</div>
                </div>
				
                <div class="row">
                    <div class="col-md-6 no-padding sm-p-l-10">
                  
                             <?= $this->formElement($form->get('remember_me')); ?> 
                            <label for="remember_me"><?php echo $this->translate('Keep Me Signed in') ?></label>
                
                    </div>
                </div>

			
			<?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
                <button class="btn btn-primary btn-cons m-t-10" type="submit"><?php echo $this->translate('Sign in') ?></button>
            </form>
			
        </div>
    </div>