<?php
$title = $this->translate('Change Password');
$this->headTitle($title);

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
           $this->translate('Users')=>$this->url('users'),
           $this->translate('Change Password') =>$this->url('users', ['action'=>'change-password', 'id'=>$user->getId()])
            ]);
$this->pageBreadcrumbs()->setIcon('fa fa-user ');
$this->actionButtons()->setItems([
           $this->translate('Back to Users') =>$this->url('users')
            ]);
$form->get('old_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter old password'
    ]);

$form->get('new_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter new password'
    ]);

$form->get('confirm_new_password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Re-enter new password'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>



<div class="row">
  <div class="col-xl-12 col-lg-12 no-padding">
    
<div class="clearfix"></div><br/>
<?= $this->flashMessenger()->render('error', ['alert', 'alert-danger']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
<div class="clearfix"></div>


<div class="col-md-6">
    <?= $this->form()->openTag($form); ?>

    <div class="form-group form-group-default">
        <?= $this->formLabel($form->get('old_password')); ?>
        <?= $this->formElement($form->get('old_password')); ?>
        <?= $this->formElementErrors($form->get('old_password')); ?>
    </div>

    <div class="form-group form-group-default">
        <?= $this->formLabel($form->get('new_password')); ?>
        <?= $this->formElement($form->get('new_password')); ?>
        <?= $this->formElementErrors($form->get('new_password')); ?>
    </div>

    <div class="form-group form-group-default">
        <?= $this->formLabel($form->get('confirm_new_password')); ?>
        <?= $this->formElement($form->get('confirm_new_password')); ?>
        <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
    </div>

    <?= $this->formElement($form->get('csrf')); ?>

    <?= $this->formElement($form->get('submit')); ?>

    <?= $this->form()->closeTag(); ?>
</div> 
    </div>
</div>
