<?php
$title = $this->translate('Reset Password');
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('settings');
$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Email address'
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
    ]);

$form->prepare();
?>

      <div class="login-container alt bg-white">
        <div class="p-l-30 m-l-15 p-r-30 m-r-15 p-t-30 m-t-20 sm-p-l-10 sm-p-r-10 sm-p-t-20">
           <?php 
  $path = $_SERVER['DOCUMENT_ROOT'].$this->basePath()."/uploads/".$this->SystemSettings()->getCompanyLogo();
  echo (file_exists($path)? '<img class="m-t-5" src="'.$this->basePath().'/uploads/logo.png" height="30"/>': '<i class="fa fa-anchor"></i><span>PlinthstoneLMS</span>');			  
?>
	
        <?= $this->form()->openTag($form); ?>

        <h2><?php echo $this->translate('Reset Password') ?></h2>

        <p><?php echo $this->translate('Enter your e-mail address below to reset your password') ?></p>

        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>                              

		<br/>
        <?= $this->formElement($form->get('captcha')); ?>
        <p class="hint"><?php echo $this->translate('Enter the letters above as you see them.') ?></p>
		<br/>
        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
		
        </div>
    </div>
