<?php
$title = $this->translate('Followups');
$this->headTitle($title);
$this->pageBreadcrumbs()->setItems([
            $this->translate('Followups')=>$this->url('followups'),
            ]);
$this->pageBreadcrumbs()->setIcon('fa fa-headphones');
$this->mainMenu()->setActiveItemId('leads');
?>

<div class="row">
  <div class="col-xl-12 col-lg-12 ">

		<?= $this->flashMessenger()->render('error', ['alert', 'alert-danger']); ?>
		<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
		<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
		<div class="clearfix"></div>


<form class="form-inline"  id="filter_form" name="leads_filter_form" method="post" action="<?php echo $this->url('followups', array('controller' => 'followups', 'action'=>'index')); ?>">
	<div class="row">

		<div class="col-md-1 hidden-sm">
		<div class="form-group">
		<input type="text" placeholder="ID" style="width:70px" name="s_id" class="form-control" value="<?= empty($search_array)?'':$search_array['s_id']; ?>" />
		</div>
		</div>

		<div class="col-md-2 col-sm-6">
		<div class="form-group">
		<select class="form-control" name="s_customer" data-init-plugin="select2">
 		<option value=""><?php echo $this->translate('Select Customer') ?></option>
 		  <?php foreach ($this->customers  as $customer){ ?>
 		  <option <?= empty($search_array)?'':($search_array['s_customer']==$customer->getId()?'selected':''); ?> value="<?php echo $customer->getId(); ?>"><?php echo $customer->getFirstName().' '.$customer->getLastName(); ?></option>
 		  <?php } ?>
 		  </select>
		</div>
		</div>

		 <div class="col-md-2 col-sm-6">
		<div class="form-group">
		  <select class="form-control" name="s_project" data-init-plugin="select2">
				<option value=""><?php echo $this->translate('Select Project') ?></option>
		  <?php foreach ($this->projects  as $project){ ?>
		  <option <?= empty($search_array)?'':($search_array['s_project']==$project->getId()?'selected':''); ?> value="<?php echo $project->getId(); ?>"><?php echo $project->getName(); ?></option>
		  <?php } ?>
		  </select>
		 </div>
		 </div>

		 <div class="col-md-2 col-sm-6">
		 <div class="form-group">
		  <select class="form-control" name="s_campaign" data-init-plugin="select2">
				<option value=""><?php echo $this->translate('Select Campaign') ?></option>
		  <?php foreach ($this->campaigns  as $campaign){ ?>
		  <option <?= empty($search_array)?'':($search_array['s_campaign']==$campaign->getId()?'selected':''); ?> value="<?php echo $campaign->getId(); ?>"><?php echo $campaign->getCampaignName(); ?></option>
		  <?php } ?>
		  </select>
		 </div>
		 </div>

		 <div class="col-md-3 col-sm-6">
		 <div class="form-group">
		  <select class="form-control" name="s_status" data-init-plugin="select2">
				<option value=""><?php echo $this->translate('Status') ?></option>
		  <?php foreach ($this->status  as $status){ ?>
		  <option <?= empty($search_array)?'':($search_array['s_status']==$status->getId()?'selected':''); ?> value="<?php echo $status->getId(); ?>"><?php echo $status->getName(); ?></option>
		  <?php } ?>
		  </select>
		 </div>
		 </div>
		 
		 <div class="col-md-2 col-sm-6">
		 <div class="form-group">
		  <select class="form-control" name="s_source" data-init-plugin="select2">
				<option value=""><?php echo $this->translate('Source') ?></option>
		  <?php foreach ($this->source  as $source){ ?>
		  <option <?= empty($search_array)?'':($search_array['s_source']==$source->getId()?'selected':''); ?> value="<?php echo $source->getId(); ?>"><?php echo $source->getName(); ?></option>
		  <?php } ?>
		  </select>
		 </div>
		 </div>

		<div class="col-md-3 col-sm-4">
		<div class="form-group">
		  <select class="form-control" name="s_lead_owner" data-init-plugin="select2">
		<option value=""><?php echo $this->translate('Select Lead Owner') ?></option>
		  <?php foreach ($this->users  as $user){ ?>
		  <option  <?= empty($search_array)?'':($search_array['s_lead_owner']==$user->getId()?'selected':''); ?> name="s_user_id" value="<?php echo $user->getId(); ?>"><?php echo $user->getFullName(); ?></option>
		  <?php } ?>
		  </select>
		</div>
		</div>

		<div class="col-md-3 col-sm-4">
		<div class="form-group">
			<div class="input-prepend input-group">
				<input type="text" style="width: 100%" name="daterange" id="daterangepicker" class="form-control" value="01/01/2018 - <?php echo date("d/m/Y"); ?>" />
			</div>
		</div>
		</div>
		
		<div class="col-md-1 col-sm-4">
		<div class="form-group">
		<button type="submit" class="btn btn-primary"><?php echo $this->translate('Filter') ?></button>
		</div>
		</div>

		 </div>
</form>

<div class="table-responsive">
	<table class="table table-hover  table-responsive-block">
	<thead>
	<tr>
		<th></th>
		<th><?php echo $this->translate('Customer Name') ?></th>
		<th><?php echo $this->translate('Contact No') ?></th>
		<th><?php echo $this->translate('Status') ?></th>
		<th><?php echo $this->translate('Source') ?></th>
		<th><?php echo $this->translate('Project') ?></th>
		<th><?php echo $this->translate('Followup Type') ?></th>
		<th><?php echo $this->translate('Follow Date') ?></th>
		<th width="100"></th>
	</tr>
	</thead>
	<tbody>

	<?php foreach ($leads as $lead) : ?>
	<tr>
	<td><?php echo $lead['l_id'];?></td>
	<td><a href="<?php echo $this->url('leads', ['action'=>'edit','id' => $lead['l_id']]); ?>"><?php echo $lead['l_firstName'].' '.$lead['l_lastName']; ?></a></td>
	<td><?php echo $lead['l_contact']; ?></td>
	<td><i class="status fa fa-circle" style="color:<?php echo $this->LeadStatusDetail()->getColor($lead['l_status']); ?>"></i></td>
	<td><i class="<?php echo $this->LeadSourceDetail()->getIcon($lead['l_source']); ?>"></i></td>
	<td><?php echo $this->ProjectDetails()->getName($lead['l_project']);?></td>
	<td><?php echo $this->FollowupDetail()->getFollowupType($lead['f_followupType']);?></td>
	<td><?php echo empty($lead['f_followDate'])?0:$lead['f_followDate']->format('d-m-Y');?></td>
	<td>
		<div class="btn-group pull-right">
		<a href="#"  data-toggle="modal" data-target="#confirmCall" class="btn btn-success btn-xs"><i class="fal fa-phone"></i></a>
			<a onclick="setcontactno(<?php echo $lead['l_contact'];?>)" href="<?php echo $this->url('notifications', array('controller' => 'notifications', 'action'=>'sendsms','id' => $lead['l_id'])); ?>" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#smsmodal"><i class="fal fa-comment-alt"></i></a>
			<a onclick="setemailadd('<?php echo $lead['l_email'];?>', <?php echo $lead['l_id'];?>)" href="<?php echo $this->url('notifications', array('controller' => 'notifications', 'action'=>'sendemail','id' => $lead['l_id'])); ?>" class="btn btn-success btn-xs" data-toggle="modal" data-target="#emailmodal"><i class="fal fa-envelope-open"></i></a>
      <a href="<?php echo $this->url('leads', array('controller' => 'leads', 'action'=>'details','id' => $lead['l_id'])); ?>" class="btn btn-info btn-xs"><i class="fa fa-bars"></i></a>
		</div>
	</td>
	</tr>
	<?php endforeach; ?>

	<?php
	function empty_filter($var){
	  if (!empty($var)){
		return $var->getName();
	  }
	}
	?>
	</tbody>
	</table>
</div>

    </div>
</div>

<?php echo $this->partial('application/partial/paginator', ['paginator'=>$this->paginator,'search'=>base64_encode(serialize($search_array))]); ?>


<!--SMS Modal-->
<div class="modal fade" id="smsmodal" tabindex="-1" role="dialog" aria-hidden="true">
<div class="modal-dialog modal-lg">
  <div class="modal-content">
	<form name="sendsms_form" method="post" action="<?php echo $this->url('notifications', array('controller' => 'notifications', 'action'=>'sendsms')); ?>">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
				<h4 class="modal-title" id="myModalLabel">Send SMS</h4>
			</div>
			<div class="modal-body">
			<div class="form-group">
			<input type="text" id="smscontactno" name="contact" class="form-control" value="" readonly></input>
			</div>
			<div class="form-group">
				<select id="smstemplate" name="smstemplate" class="form-control">
				<option value="">Select</option>
				<?php foreach ($smstemplates as $smstemplate) : ?>
				<option value="<?php echo $smstemplate->getID();?>"><?php echo $smstemplate->getTitle();?></option>
				<?php endforeach; ?>
				</select>
			</div>

			<div class="form-group">
				<textarea id="message" readonly name="message" class="form-control">

				</textarea>
			</div>
			</div>
			<div class="modal-footer">
				<button class="btn btn-primary" type="submit"><?php echo $this->translate('Submit') ?></button>
			</div>
		</form>
  </div>
</div>
</div>

<!-- Modal Dialog -->
<div class="modal fade" id="confirmCall" role="dialog" aria-labelledby="confirmCallLabel" aria-hidden="true">
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h4 class="modal-title"><?php echo $this->translate('Call Customer') ?></h4>
    </div>
    <div class="modal-body">
      <p><?php echo $this->translate('Are you sure you want to make this call?') ?></p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
      <button type="button" class="btn btn-success" id="confirm"><?php echo $this->translate('Call') ?></button>
    </div>
  </div>
</div>
</div>

<!--Email Modal-->
<div class="modal fade" id="emailmodal" tabindex="-1" role="dialog" aria-hidden="true">
<div class="modal-dialog modal-lg">
  <div class="modal-content">
	<form name="sendemail_form" method="post" action="<?php echo $this->url('notifications', array('controller' => 'notifications', 'action'=>'sendemail')); ?>">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
				<h4 class="modal-title" id="myModalLabel"><?php echo $this->translate('Send Email') ?></h4>
			</div>
			<div class="modal-body">
			<div class="form-group">
			<input id="modalemailadd" type="text" name="email" class="form-control" value="" readonly></input>
			</div>
			<div class="form-group">
				<select id="emailtemplate" name="emailtemplate" class="form-control">
				<option value="">Select</option>
				<?php foreach ($emailtemplates as $emailtemplate) : ?>
				<option value="<?php echo $emailtemplate->getID();?>"><?php echo $emailtemplate->getTitle();?></option>
				<?php endforeach; ?>
				</select>
			</div>
			<input id="modalleadid" type="hidden" name="lead_id" class="form-control" value="<?php echo $this->lead_id; ?>" readonly></input>
			<div class="form-group">
				<textarea id="message2" readonly name="message" class="form-control">

				</textarea>
			</div>
			</div>
			<div class="modal-footer">
				<button class="btn btn-primary" type="submit"><?php echo $this->translate('Submit') ?></button>
			</div>
		</form>
  </div>
</div>
</div>


<style>
.fa-mobile-phone::before, .fa-mobile::before {
    content: "\f10b";
    font-size: 18px;
}
.form-inline .form-group {
    margin-right: 10px;
    margin-bottom: 10px;
}
#daterangepicker10, .input-prepend{
	width: 100% !important;
}
</style>
<script src="<?php echo $this->basePath(); ?>/plugins/ckeditor.js"></script>
<script>
ClassicEditor
	.create( document.querySelector( '#message2' ) )
	.then( editor => {
		window.myEditor = editor
	});
</script>
