<?php
$title = $this->translate('Edit Amenities');
$this->headTitle($title);
$this->pageBreadcrumbs()->setItems([
            $this->translate('Amenities')=>$this->url('amenities'),
            $this->translate('Edit')=>$this->url('amenities', ['action'=>'edit']),
            ]);
$this->pageBreadcrumbs()->setIcon('fa fa-shopping-bag');
$this->actionButtons()->setItems([
            $this->translate('Back to Amenities')=>$this->url('amenities')
            ]);
			
$this->mainMenu()->setActiveItemId('masters');

$form->get('name')->setAttributes(['class'=>'form-control', 'placeholder'=>'Name']);
$form->get('status')->setAttributes(['class'=>'form-control','data-init-plugin' => 'switchery']);
$form->get('type')->setAttributes(['class'=>'form-control','data-init-plugin' => 'select2']);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary'])->setValue($this->translate('Save'));
$form->prepare();
?>


<div class="row">
  <div class="col-xl-12 col-lg-12 no-padding">
<div class="clearfix"></div><br/>
<?= $this->flashMessenger()->render('error', ['alert', 'alert-danger']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
<div class="clearfix"></div>

<?= $this->form()->openTag($form); ?>
<div class="col-md-6">
<div class="form-group form-group-default">
    <?= $this->formLabel($form->get('name')); ?>
    <?= $this->formElement($form->get('name')); ?>
    <?= $this->formElementErrors($form->get('name')); ?>
</div>

<div class="form-group form-group-default form-group-default-select2">
    <?= $this->formLabel($form->get('type')); ?>
    <?= $this->formElement($form->get('type')); ?>
    <?= $this->formElementErrors($form->get('type')); ?>
</div>

<div class="form-group form-group-default switchery_holder">
    <?= $this->formLabel($form->get('status')); ?>
    <?= $this->formElement($form->get('status')); ?>
    <?= $this->formElementErrors($form->get('status')); ?>
</div>

<?= $this->formElement($form->get('submit')); ?>
</div>
<?= $this->form()->closeTag(); ?>

    </div>
</div>
