<!-- footer content -->
<div class=" container   container-fixed-lg footer">
  <div class="copyright sm-text-center">
    <p class="small no-margin pull-left sm-pull-reset">
      <span class="hint-text"><?php echo $this->translate('crafted with') ?> <i style="color:#f55753;" class="fa fa-heart"></i> <?php echo $this->translate('by') ?> <a href="http://www.ajazsiddiqui.me"><?php echo $this->translate('ajazsiddiqui') ?></a> &copy;
        <?= date('Y') ?>
      </span>.
      <span class="hint-text"><?php echo $this->translate('All rights reserved.') ?>
      </span>
    </p>
    <p class="small no-margin pull-right sm-pull-reset"><?php echo $this->translate('Supports best on Google Chrome, Safari and Firefox.') ?>
    </p>
    <div class="clearfix">
    </div>
  </div>
</div>
<!-- /footer content -->
