<div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="1">
<a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu"><i class="fal fa-times-circle"></i>
</a>
<a href="<?php echo $this->url("home");?>"><img class="plinthstone_logo" src="<?= $this->basePath().'/plinthstone_logo.svg';?>"/></a>
	<?php
		if (isset($activeMenuItemId)) {
		$this->mainMenu()->setActiveItemId($activeMenuItemId);
		}
		echo $this->mainMenu()->renderMenu();
	?>
</div>