<?php
$title = $this->translate('Edit Role');
$this->headTitle($title);

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Roles')=>$this->url('roles'),
            $this->translate('Edit')=>$this->url('roles', ['action'=>'edit'])
            ]);
			
$this->actionButtons()->setItems([
            $this->translate('Back to Role')=>$this->url('roles')
            ]);
$this->pageBreadcrumbs()->setIcon('fa fa-key');
$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter name'
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter description'
    ]);

$form->get('inherit_roles[]')->setAttributes([
    'class'=>'form-control' ,'data-init-plugin' => 'select2'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary'])->setValue($this->translate('Save'));

$form->prepare();
?>


<div class="row">
  <div class="col-sm-12 col-md-6 no-padding">
    <div class="clearfix"></div><br/>
<?= $this->flashMessenger()->render('error', ['alert', 'alert-danger']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
<div class="clearfix"></div>

<?= $this->form()->openTag($form); ?>



        <div class="form-group form-group-default">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group form-group-default">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group form-group-default form-group-default-select2">
            <?= $this->formLabel($form->get('inherit_roles[]')); ?>
            <?= $this->formElement($form->get('inherit_roles[]')); ?>
            <?= $this->formElementErrors($form->get('inherit_roles[]')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

<?= $this->form()->closeTag(); ?>
     
    </div>
</div>
