<?php
$title = $this->translate('Edit Role Permissions');
$this->headTitle($title);

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Roles')=>$this->url('roles'),
           $this->translate('Edit Permission') =>$this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()])
            ]);

$this->actionButtons()->setItems([
            $this->translate('Back to Role')=>$this->url('roles')
            ]);
$this->pageBreadcrumbs()->setIcon('fa fa-key');			
$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue($this->translate('Save'));

$form->prepare();
?>

<div class="row">
  <div class="col-xl-12 col-lg-12 ">
    
<div class="clearfix"></div><br/>
<?= $this->flashMessenger()->render('error', ['alert', 'alert-danger']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
<div class="clearfix"></div>

<div class="col-md-8">
    <?= $this->form()->openTag($form); ?>
    <div class="table-responsive">
		<table class="table table-hover  table-responsive-block">
			<?php
			$i = 1;
			foreach ($allPermissions as $permission):
				$element = $form->get('permissions')->get($permission->getName());
			?>
			<tr>
				<td>
				
					<div class="checkbox check-primary checkbox-circle">
						<input id="checkbox<?= $i ?>" type="checkbox" name="<?= $this->escapeHtmlAttr($element->getName()) ?>"
									  value="<?= $this->escapeHtmlAttr($element->getCheckedValue()) ?>"
									  <?php if ($element->isChecked()) echo 'checked'?>
									  <?php if ($element->getAttribute('disabled')) echo 'disabled'?>>
						 <label for="checkbox<?= $i ?>">
						 <?= $this->escapeHtml($element->getLabel()) ?>
						</label>
						<?= $this->formElementErrors($element); ?>
					</div>
				</td>
				<td>
					<?= $this->escapeHtml($permission->getDescription()) ?>
				</td>
			</tr>
			<?php 
			$i++;
			endforeach; ?>
		</table>
  </div>
  <br/><br/> 
    <?= $this->formElement($form->get('csrf')); ?>

    <?= $this->formElement($form->get('submit')); ?>

    <?= $this->form()->closeTag(); ?>
</div>
    </div>
</div>

<style>
.table td, .table th {
    padding: 0;
    border-top: 0;
}
</style>
