<?php
$title = $this->translate('Roles');
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Roles')=>$this->url('roles'),
            $this->translate('Manage')=>$this->url('roles'),
            ]);
$this->pageBreadcrumbs()->setIcon('fa fa-key');			
$this->actionButtons()->setItems([
            $this->translate('Add Role')=>$this->url('roles',['action'=>'add']),
            ]);
?>

<div class="row">
  <div class="col-xl-12 col-lg-12 ">
    <div class="clearfix"></div><br/>
<?= $this->flashMessenger()->render('error', ['alert', 'alert-danger']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
<div class="clearfix"></div>



<div class="table-responsive">
<table class="table table-hover  table-responsive-block">
<thead>
   <tr>
        <th><?php echo $this->translate('ID') ?></th>
        <th><?php echo $this->translate('Name') ?></th>
        <th><?php echo $this->translate('Description') ?></th>
        <th><?php echo $this->translate('Date Created') ?></th>
        <th><?php echo $this->translate('Actions') ?></th>
    </tr>
  </thead>
    <?php foreach ($roles as $role): ?>

    <tr>
        <td><?= $this->escapeHtml($role->getId()); ?></td>
        <td>
            <a href="<?= $this->url('roles', ['action'=>'view', 'id'=>$role->getId()]); ?>">
                <?= $this->escapeHtml($role->getName()); ?>
            </a>
        </td>
        <td><?= $this->escapeHtml($role->getDescription()); ?></a>
        </td>
        <td><nobr><?= $this->escapeHtml($role->getDateCreated()); ?></nobr></td>
        <td>
            <div class="btn-group pull-right">
            <a class="btn btn-info btn-xs" href="<?= $this->url('roles',
                    ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                <i class="fal fa-edit" ></i>
            </a>
            <a class="btn btn-danger btn-xs" href="#" data-link="<?= $this->url('roles',
                    ['action'=>'delete', 'id'=>$role->getId()]); ?>" data-toggle="modal" data-target="#confirmDelete">
                <i class="far fa-trash-alt"></i>
            </a>
          </div>
        </td>
    </tr>

    <?php endforeach; ?>

</table>
</div>
    </div>
</div>

<?php echo $this->partial('application/index/delete'); ?>
