<?php
$title = $this->translate('Edit Permission');
$this->headTitle($title);

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
           $this->translate('Permissions')=>$this->url('permissions'),
           $this->translate('Edit')=>$this->url('permissions', ['action'=>'edit'])
            ]);
$this->actionButtons()->setItems([
           $this->translate('Back to Permissions')=>$this->url('permissions')
            ]);
$this->pageBreadcrumbs()->setIcon('fa fa-lock');
$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter name'
    ]);

$form->get('description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter description'
    ]);


$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue($this->translate('Save'));
$form->prepare();
?>


<div class="row">
  <div class="col-xl-12 col-lg-12 no-padding">
    <div class="clearfix"></div><br/>
<?= $this->flashMessenger()->render('error', ['alert', 'alert-danger']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
<div class="clearfix"></div>

<div class="col-md-6">
    <?= $this->form()->openTag($form); ?>

    <div class="form-group">
        <?= $this->formLabel($form->get('name')); ?>
        <?= $this->formElement($form->get('name')); ?>
        <?= $this->formElementErrors($form->get('name')); ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('description')); ?>
        <?= $this->formElement($form->get('description')); ?>
        <?= $this->formElementErrors($form->get('description')); ?>
    </div>

    <?= $this->formElement($form->get('csrf')); ?>

    <?= $this->formElement($form->get('submit')); ?>

    <?= $this->form()->closeTag(); ?>
</div>  
    </div>
</div>
