<?php
$title = $this->translate('Dashboard');
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('home');
$this->pageBreadcrumbs()->setItems([
            $this->translate('Dashboard')=>$this->url('home')
            ]);
$this->pageBreadcrumbs()->setIcon('fa fa-desktop');
?>

<div class="container sm-padding-10 no-padding">

    <div class="row">
        <div class="col-lg-3 col-sm-6 d-flex flex-column">


            <div class="card social-card share  full-width m-b-10" data-social="item">
                <div class="card-header ">
                    <h5 class="text-complete pull-left fs-12"><?php echo $this->translate('News') ?> <i class="status fa fa-circle text-complete fs-11"></i></h5>
                    <div class="clearfix"></div>
                </div>
                <div class="card-description">
                    <h3>We Want To Be Seen As The Partner Of Choice For Large Developers</h3>
                </div>
                <div class="card-footer clearfix">
                    <div class="pull-left">via <span class="text-complete"><a href="https://realtynxt.com/2018/08/25/we-want-to-be-seen-as-the-partner-of-choice-for-large-developers-centrum-rema/">RealtyNXT</a></span>
                    </div>
                    <div class="pull-right hint-text">
                       <?php echo date("M d"); ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>



            <div class="card widget-loader-bar m-b-10">
                <div class="container-xs-height full-height">
                    <div class="row-xs-height">
                        <div class="col-xs-height col-top">
                            <div class="card-header  top-left top-right">
                                <div class="card-title">
                                    <span class="font-montserrat fs-11 all-caps"><?php echo $this->translate('Total Leads') ?> <i class="fa fa-chevron-right"></i>
      </span>
                                </div>
                                <div class="card-controls">
                                    <ul>
                                        <li><a href="#" class="portlet-refresh text-black" data-toggle="refresh"><i class="portlet-icon portlet-icon-refresh"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-xs-height">
                        <div class="col-xs-height col-top">
                            <div class="p-l-20 p-t-50 p-b-40 p-r-20">
                                <h3 class="no-margin p-b-5"><?php echo $this->leads['all']; ?></h3>
                                <span class="small hint-text pull-left"><?php echo $this->leads['week']; ?> <?php echo $this->translate('this week') ?></span>
                                <span class="pull-right small text-primary"><?php echo $this->leads['month']; ?> <?php echo $this->translate('this month') ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="row-xs-height">
                        <div class="col-xs-height col-bottom">
                            <div class="progress progress-small m-b-0">

                                <div class="progress-bar progress-bar-primary" style="width:71%"></div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>


            

        </div>
        <div class="col-lg-3 col-sm-6 d-flex flex-column">

            <div class="card social-card share  full-width m-b-10" data-social="item">
                <div class="card-header clearfix">
                    <h5 class="text-success pull-left fs-12"><?php echo $this->translate('Quick Followup') ?> <i class="status fa fa-circle text-success fs-11"></i></h5>
                    <div class="pull-right small hint-text">
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="card-description">
                    <?php foreach ($this->leadstofollow as $follow){ ?>
						<h6 class="hint-text no-margin"><?php echo $follow['l_firstName']; ?> <?php echo $follow['l_lastName']; ?> <i class="status fa fa-circle" style="color:<?= $this->LeadStatusDetail()->getColor($follow['l_status']); ?>"></i> </h6>
						<span class="small hint-text pull-left"><?php echo $this->FollowupDetail()->getFollowupType($follow['f_followupType']); ?>  <?= empty($follow['f_followDate'])?'':$follow['f_followDate']->format('d M'); ?></span>
						<br/>
						<div class="btn-group m-b-10">
							<a href="#" data-toggle="modal" data-target="#confirmCall" class="btn btn-success btn-xs"><i class="fal fa-phone"></i></a>
							<a onclick="setcontactno(<?php echo $follow['l_contact']; ?> )" href="<?= $this->url('notifications',['action'=>'sendsms','id'=>$follow['l_id']]); ?>" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#smsmodal"><i class="fal fa-comment-alt"></i></a>
							<a onclick="setemailadd('<?php echo $follow['l_email']; ?> ', 7)" href="<?= $this->url('notifications',['action'=>'sendemail','id'=>$follow['l_id']]); ?>" class="btn btn-success btn-xs" data-toggle="modal" data-target="#emailmodal"><i class="fal fa-envelope-open"></i></a>
							<a href="<?= $this->url('leads',['action'=>'edit','id'=>$follow['l_id']]); ?>" class="btn btn-complete btn-xs"><i class="fal fa-edit"></i></a>
						</div>
						
				<br/>
					<?php } ?>	
                </div>

            </div>

<div class="card widget-loader-bar m-b-10">
                <div class="container-xs-height full-height">
                    <div class="row-xs-height">
                        <div class="col-xs-height col-top">
                            <div class="card-header  top-left top-right">
                                <div class="card-title">
                                    <span class="font-montserrat fs-11 all-caps"><?php echo $this->translate('Total SiteVisits') ?> <i class="fa fa-chevron-right"></i>
      </span>
                                </div>
                                <div class="card-controls">
                                    <ul>
                                        <li><a href="#" class="portlet-refresh text-black" data-toggle="refresh"><i class="portlet-icon portlet-icon-refresh"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-xs-height">
                        <div class="col-xs-height col-top">
                            <div class="p-l-20 p-t-50 p-b-40 p-r-20">
                                <h3 class="no-margin p-b-5"><?php echo $this->converts['all']; ?></h3>
                                <span class="small hint-text pull-left"><?php echo $this->converts['week']; ?> <?php echo $this->translate('this week') ?></span>
                                <span class="pull-right small text-primary"><?php echo $this->converts['month']; ?> <?php echo $this->translate('this month') ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="row-xs-height">
                        <div class="col-xs-height col-bottom">
                            <div class="progress progress-small m-b-0">

                                <div class="progress-bar progress-bar-danger" style="width:15%"></div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 m-b-10 d-flex flex-column">

            <div class="widget-12 card widget-loader-circle no-margin col ar-1-1 sm-vh-75">
                
                <div class="card-block d-flex flex-column">
                    <div class="">
                        <div class="d-flex flex-row">
                          <div class="padding-25" style="padding:0 !important">
                  <div class="col-6 pull-left">
                      <h2 class="text-success no-margin"><?php echo $this->translate('Lead Sources') ?></h2>
                      <p class="no-margin"><?php echo $this->translate('Leads &amp; Site Visit') ?></p>
                  </div>
                  <div class="col-6 pull-left">
						<form id="leadsource_form" style="margin:20px 0;" method="post" action="">
						<div class="col-md-10 pull-left no-padding">
						  <div class="form-group">
							<select name="s_project" id="s_project" class="form-control" required="" data-init-plugin = "select2">
							<option value="">All Projects</option>
							<?php foreach ($this->projects as $key => $value){
							  $selected = ((@$_POST['s_project']==$key)?'selected':'');
							  echo '<option value="'.$key.'"'.$selected.'>'.$value.'</option>';
							}
							?>
							</select>
							<input id="currentp" type="hidden" value="<?= !empty($_POST['s_project'])?$_POST['s_project']:'' ; ?>" />
						  </div>
						  </div>
						  <div class="col-md-2 pull-left no-padding">
						  <button type="submit"  id="processLeadSourceChart" class="btn btn-primary"><i class="fa fa-search"></i></button>
						  </div>
						  </form>
					  </div>
                   
                  <div class="clearfix"></div>
              </div>
                        </div>
						
                        <div class="full-width">
<div id="barContainer" style="min-width: 300px; max-width: 100%; height: 250px; margin: 0 auto; margin-top:50px;"></div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>


    <div class="row m-b-30">



<div class="col-lg-6 sm-m-t-12 d-flex align-items-stretch mob-m-b-30">

    <div class="widget-11-2 card card-condensed no-margin widget-loader-circle d-flex flex-column align-self-stretch">
        <div class="card-header top-right">
            <div class="card-controls">
                <ul>
                    <li><a data-toggle="refresh" class="portlet-refresh text-black" href="#"><i class="portlet-icon portlet-icon-refresh"></i></a>
                    </li>
                </ul>
            </div>				
        </div>
        <div class="padding-25">
            <div class="pull-left">
                <h2 class="text-success no-margin"><?php echo $this->translate('Pipeline Reports') ?></h2>
                <p class="no-margin"><?php echo $this->translate('Total Leads') ?></p>
            </div>
				  
            <div class="clearfix"></div>
        </div>
        <div class="auto-overflow widget-11-2-table">
              <div id="container" style="min-width: 300px; max-width: 470px; height: 270px; margin: 0 auto"></div>
        </div>
        <div class="padding-25 mt-auto">

        </div>
    </div>

</div>



        <div class="col-lg-6 sm-m-t-12 d-flex align-items-stretch">

            <div class="widget-11-2 card card-condensed no-margin widget-loader-circle d-flex flex-column align-self-stretch">
                <div class="padding-25">
                    <div class="pull-left">
                        <h2 class="text-success no-margin"><?php echo $this->translate('Leader Board') ?></h2>
                        <p class="no-margin"><?php echo $this->translate('Users Performance') ?></p>
                    </div>
                    <h3 class="pull-right semi-bold"><sup>
      <small class="semi-bold"></small>
    </sup>
                    </h3>
                    <div class="clearfix"></div>
                </div>
                <div class="auto-overflow widget-11-2-table">
                    <table class="table  table-hover">
                        <tbody>
                          <tr>
                              <td class="font-montserrat all-caps fs-12 w-50"></td>
                              <td class="text-right b-r b-dashed b-grey w-25">
                                  <span class="hint-text small"><?php echo $this->translate('Enquiry') ?></span>
                              </td>
                              <td class="w-25" width="35">
                                  <span class="font-montserrat fs-18"><?php echo $this->translate('Sitevisits') ?></span>
                              </td>
                          </tr>

                          <?php for ($i = 0; $i < count($this->leaderboard['usernames']); $i++) { ?>

                            <tr>
                                <td class="font-montserrat all-caps fs-12 w-50"><?php echo $this->leaderboard['usernames'][$i]; ?></td>
                                <td class="text-right b-r b-dashed b-grey w-25">
                                    <span class="hint-text small"><?php echo $this->leaderboard['enquiries'][$i]; ?></span>
                                </td>
                                <td class="text-right b-r b-dashed b-grey w-25">
                                    <span class="hint-text small"><?php echo $this->leaderboard['sitevisits'][$i]; ?></span>
                                </td>
                            </tr>
                          <?php } ?>
                        </tbody>
                    </table>
                </div>
                <div class="padding-25 mt-auto">
                    <p class="small no-margin">
                        <a href="<?php echo $this->url('followups', array('controller' => 'followups', 'action'=>'index')); ?>"><i class="fa fs-16 fa-arrow-circle-o-down text-success m-r-10"></i></a>
                        <span class="hint-text "><?php echo $this->translate('Show more details of FollowUps') ?></span>
                    </p>
                </div>
            </div>

        </div>
    </div>


    <div class="row m-b-30">
        <div class="col-lg-12 sm-m-t-12 d-flex align-items-stretch">

            <div class="widget-11-2 card card-condensed no-margin widget-loader-circle d-flex flex-column align-self-stretch">
                <div class="card-header top-right">
                    <div class="card-controls">
                        <ul>
                            <li><a data-toggle="refresh" class="portlet-refresh text-black" href="#"><i class="portlet-icon portlet-icon-refresh"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="padding-25">
                    <div class="pull-left">
                        <h2 class="text-success no-margin"><?php echo $this->translate('Projects Prospect Chart') ?></h2>
                        <p class="no-margin"><?php echo $this->translate('Leads & Site Visit') ?></p>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="auto-overflow widget-11-2-table">
                    <div id="barProjectContainer"  style="min-width: 300px; max-width: 100%; height: 270px; margin: 0 auto"></div>
                </div>
                <div class="padding-25 mt-auto">

                </div>
            </div>

        </div>
    </div>


</div>

